import comp from "E:/code/newstudy/new/dromara.github.io/src/.vuepress/.temp/pages/zh/blog/ApacheShenYu-2.6.1.html.vue"
const data = JSON.parse("{\"path\":\"/zh/blog/ApacheShenYu-2.6.1.html\",\"title\":\"Apache ShenYu 2.6.1 Released\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"Apache ShenYu 2.6.1 Released\",\"author\":\"何凤恩\",\"date\":\"2024-01-24T00:00:00.000Z\",\"cover\":\"/assets/img/blog/ApacheShenYu-2.6.1-0.png\",\"head\":[[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"Apache ShenYu 2.6.1 Released\\\",\\\"image\\\":[\\\"https://vuepress-theme-hope-docs-demo.netlify.app/assets/img/blog/ApacheShenYu-2.6.1-0.png\\\",\\\"https://vuepress-theme-hope-docs-demo.netlify.app/assets/img/blog/ApacheShenYu-2.6.1-1.png\\\",\\\"https://vuepress-theme-hope-docs-demo.netlify.app/assets/img/blog/ApacheShenYu-2.6.1-2.png\\\",\\\"https://vuepress-theme-hope-docs-demo.netlify.app/assets/img/blog/ApacheShenYu-2.6.1-3.png\\\"],\\\"datePublished\\\":\\\"2024-01-24T00:00:00.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"何凤恩\\\"}]}\"],[\"meta\",{\"property\":\"og:url\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/zh/blog/ApacheShenYu-2.6.1.html\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"Apache ShenYu 2.6.1 Released\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"关于Apache ShenYu “ 官网: https://shenyu.apache.org GitHub: https://github.com/apache/shenyu 版本预览 “ 版本记录：https://github.com/apache/shenyu/compare/v2.6.0...v2.6.1 新特性 1.为shenyu ingre...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:image\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/assets/img/blog/ApacheShenYu-2.6.1-0.png\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"og:locale:alternate\",\"content\":\"en-US\"}],[\"meta\",{\"name\":\"twitter:card\",\"content\":\"summary_large_image\"}],[\"meta\",{\"name\":\"twitter:image:src\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/assets/img/blog/ApacheShenYu-2.6.1-0.png\"}],[\"meta\",{\"name\":\"twitter:image:alt\",\"content\":\"Apache ShenYu 2.6.1 Released\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"何凤恩\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2024-01-24T00:00:00.000Z\"}],[\"link\",{\"rel\":\"alternate\",\"hreflang\":\"en-us\",\"href\":\"https://vuepress-theme-hope-docs-demo.netlify.app/blog/ApacheShenYu-2.6.1.html\"}],[\"meta\",{\"name\":\"博客\"}]],\"description\":\"关于Apache ShenYu “ 官网: https://shenyu.apache.org GitHub: https://github.com/apache/shenyu 版本预览 “ 版本记录：https://github.com/apache/shenyu/compare/v2.6.0...v2.6.1 新特性 1.为shenyu ingre...\"},\"readingTime\":{\"minutes\":9.19,\"words\":2756},\"filePathRelative\":\"zh/blog/ApacheShenYu-2.6.1.md\",\"autoDesc\":true}")
export { comp, data }

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
