import comp from "E:/code/newstudy/new/dromara.github.io/src/.vuepress/.temp/pages/zh/blog/soul_source_learning_21_resilience4j.html.vue"
const data = JSON.parse("{\"path\":\"/zh/blog/soul_source_learning_21_resilience4j.html\",\"title\":\"Soul网关学习Resilience4j插件原理解析\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"Soul网关学习Resilience4j插件原理解析\",\"author\":\"yanbing\",\"tag\":[\"Soul\"],\"date\":\"2021-03-22T00:00:00.000Z\",\"cover\":\"/assets/img/blog6/03.jpg\",\"head\":[[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"Soul网关学习Resilience4j插件原理解析\\\",\\\"image\\\":[\\\"https://img-blog.csdnimg.cn/20210321112151395.png?x-oss-process=image/watermark,type_ZmFuZ3poZW5naGVpdGk,shadow_10,text_aHR0cHM6Ly9ibG9nLmNzZG4ubmV0L3FxXzM3ODY5MjQz,size_16,color_FFFFFF,t_70\\\",\\\"https://img-blog.csdnimg.cn/20210321112202189.png?x-oss-process=image/watermark,type_ZmFuZ3poZW5naGVpdGk,shadow_10,text_aHR0cHM6Ly9ibG9nLmNzZG4ubmV0L3FxXzM3ODY5MjQz,size_16,color_FFFFFF,t_70\\\"],\\\"datePublished\\\":\\\"2021-03-22T00:00:00.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"yanbing\\\"}]}\"],[\"meta\",{\"property\":\"og:url\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/zh/blog/soul_source_learning_21_resilience4j.html\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"Soul网关学习Resilience4j插件原理解析\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"目标 什么是 Resilience4J soul 的 Resilience4j 体验 限流 熔断 Resilience4J 插件源码解读 什么是 Resilience4j Resilience4J 是 Spring Cloud Gateway 推荐的容错方案，它是一个轻量级的容错库 借鉴了 Hystrix 而设计，并且采用 JDK8 这个函数式编程，即...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:image\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/assets/img/blog6/03.jpg\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"og:locale:alternate\",\"content\":\"en-US\"}],[\"meta\",{\"name\":\"twitter:card\",\"content\":\"summary_large_image\"}],[\"meta\",{\"name\":\"twitter:image:src\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/assets/img/blog6/03.jpg\"}],[\"meta\",{\"name\":\"twitter:image:alt\",\"content\":\"Soul网关学习Resilience4j插件原理解析\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"yanbing\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"Soul\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2021-03-22T00:00:00.000Z\"}],[\"link\",{\"rel\":\"alternate\",\"hreflang\":\"en-us\",\"href\":\"https://vuepress-theme-hope-docs-demo.netlify.app/blog/soul_source_learning_21_resilience4j.html\"}],[\"meta\",{\"name\":\"博客\"}]],\"description\":\"目标 什么是 Resilience4J soul 的 Resilience4j 体验 限流 熔断 Resilience4J 插件源码解读 什么是 Resilience4j Resilience4J 是 Spring Cloud Gateway 推荐的容错方案，它是一个轻量级的容错库 借鉴了 Hystrix 而设计，并且采用 JDK8 这个函数式编程，即...\"},\"readingTime\":{\"minutes\":6,\"words\":1799},\"filePathRelative\":\"zh/blog/soul_source_learning_21_resilience4j.md\",\"autoDesc\":true}")
export { comp, data }

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
