import comp from "E:/code/newstudy/new/dromara.github.io/src/.vuepress/.temp/pages/activity/dromara-cloud-native-meet.html.vue"
const data = JSON.parse("{\"path\":\"/activity/dromara-cloud-native-meet.html\",\"title\":\"Dromara Soul source code 01 reading sharing session 01\",\"lang\":\"en-US\",\"frontmatter\":{\"title\":\"Dromara Soul source code 01 reading sharing session 01\",\"author\":\"xiaoyu\",\"date\":\"2021-01-21T00:00:00.000Z\",\"tag\":[\"Soul\",\"Dromara\",\"Reactor\"],\"cover\":\"/assets/img/activity/dromara-open-soul-02.jpg\",\"head\":[[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"Dromara Soul source code 01 reading sharing session 01\\\",\\\"image\\\":[\\\"https://vuepress-theme-hope-docs-demo.netlify.app/assets/img/activite/soul-xmind.png\\\"],\\\"datePublished\\\":\\\"2021-01-21T00:00:00.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"xiaoyu\\\"}]}\"],[\"meta\",{\"property\":\"og:url\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/activity/dromara-cloud-native-meet.html\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"Dromara Soul source code 01 reading sharing session 01\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"Dromara Online ActivityDromara Online Activity Dromara source code reading (Soul 2021 first activity) Date: Sunday, January 24, 2021 Time: 15:00 – 17:00 Location: Tencent Meetin...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:image\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/assets/img/activity/dromara-open-soul-02.jpg\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"en-US\"}],[\"meta\",{\"property\":\"og:locale:alternate\",\"content\":\"zh-CN\"}],[\"meta\",{\"name\":\"twitter:card\",\"content\":\"summary_large_image\"}],[\"meta\",{\"name\":\"twitter:image:src\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/assets/img/activity/dromara-open-soul-02.jpg\"}],[\"meta\",{\"name\":\"twitter:image:alt\",\"content\":\"Dromara Soul source code 01 reading sharing session 01\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"xiaoyu\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"Reactor\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"Dromara\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"Soul\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2021-01-21T00:00:00.000Z\"}],[\"link\",{\"rel\":\"alternate\",\"hreflang\":\"zh-cn\",\"href\":\"https://vuepress-theme-hope-docs-demo.netlify.app/zh/activity/dromara-cloud-native-meet.html\"}],[\"meta\",{\"name\":\"Activity\"}]],\"description\":\"Dromara Online ActivityDromara Online Activity Dromara source code reading (Soul 2021 first activity) Date: Sunday, January 24, 2021 Time: 15:00 – 17:00 Location: Tencent Meetin...\"},\"readingTime\":{\"minutes\":0.59,\"words\":176},\"filePathRelative\":\"activity/dromara-cloud-native-meet.md\",\"autoDesc\":true}")
export { comp, data }

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
