import comp from "E:/code/newstudy/new/dromara.github.io/src/.vuepress/.temp/pages/activity/dromara-cloud-native-meet-02.html.vue"
const data = JSON.parse("{\"path\":\"/activity/dromara-cloud-native-meet-02.html\",\"title\":\"Dromara Soul Source Code 01 Reading Sharing Session 02\",\"lang\":\"en-US\",\"frontmatter\":{\"title\":\"Dromara Soul Source Code 01 Reading Sharing Session 02\",\"author\":\"xiaoyu\",\"date\":\"2021-02-06T00:00:00.000Z\",\"tag\":[\"Soul\",\"Dromara\",\"Reactor\"],\"cover\":\"/assets/img/activity/dromara-open-soul-03.jpg\",\"head\":[[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"Dromara Soul Source Code 01 Reading Sharing Session 02\\\",\\\"image\\\":[\\\"https://vuepress-theme-hope-docs-demo.netlify.app/assets/img/activite/soul-xmind.png\\\"],\\\"datePublished\\\":\\\"2021-02-06T00:00:00.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"xiaoyu\\\"}]}\"],[\"meta\",{\"property\":\"og:url\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/activity/dromara-cloud-native-meet-02.html\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"Dromara Soul Source Code 01 Reading Sharing Session 02\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"Dromara Online ActivityDromara Online Activity Dromara source code reading (Soul 2021 first activity) Date: Sunday, February 6, 2021 Time：20:00 – 23:00 Location: Tencent Meeting...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:image\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/assets/img/activity/dromara-open-soul-03.jpg\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"en-US\"}],[\"meta\",{\"property\":\"og:locale:alternate\",\"content\":\"zh-CN\"}],[\"meta\",{\"name\":\"twitter:card\",\"content\":\"summary_large_image\"}],[\"meta\",{\"name\":\"twitter:image:src\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/assets/img/activity/dromara-open-soul-03.jpg\"}],[\"meta\",{\"name\":\"twitter:image:alt\",\"content\":\"Dromara Soul Source Code 01 Reading Sharing Session 02\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"xiaoyu\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"Reactor\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"Dromara\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"Soul\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2021-02-06T00:00:00.000Z\"}],[\"link\",{\"rel\":\"alternate\",\"hreflang\":\"zh-cn\",\"href\":\"https://vuepress-theme-hope-docs-demo.netlify.app/zh/activity/dromara-cloud-native-meet-02.html\"}],[\"meta\",{\"name\":\"Activity\"}]],\"description\":\"Dromara Online ActivityDromara Online Activity Dromara source code reading (Soul 2021 first activity) Date: Sunday, February 6, 2021 Time：20:00 – 23:00 Location: Tencent Meeting...\"},\"readingTime\":{\"minutes\":0.67,\"words\":202},\"filePathRelative\":\"activity/dromara-cloud-native-meet-02.md\",\"autoDesc\":true}")
export { comp, data }

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
