import comp from "E:/code/newstudy/new/dromara.github.io/src/.vuepress/.temp/pages/blog/ApacheShenYu-2.6.1.html.vue"
const data = JSON.parse("{\"path\":\"/blog/ApacheShenYu-2.6.1.html\",\"title\":\"Apache ShenYu 2.6.1 Released\",\"lang\":\"en-US\",\"frontmatter\":{\"title\":\"Apache ShenYu 2.6.1 Released\",\"author\":\"Ho Fung Eun\",\"date\":\"2024-01-24T00:00:00.000Z\",\"cover\":\"/assets/img/blog/ApacheShenYu-2.6.1-0.png\",\"head\":[[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"Apache ShenYu 2.6.1 Released\\\",\\\"image\\\":[\\\"https://vuepress-theme-hope-docs-demo.netlify.app/assets/img/blog/ApacheShenYu-2.6.1-0.png\\\",\\\"https://vuepress-theme-hope-docs-demo.netlify.app/assets/img/blog/ApacheShenYu-2.6.1-1.png\\\",\\\"https://vuepress-theme-hope-docs-demo.netlify.app/assets/img/blog/ApacheShenYu-2.6.1-2.png\\\",\\\"https://vuepress-theme-hope-docs-demo.netlify.app/assets/img/blog/ApacheShenYu-2.6.1-3.png\\\"],\\\"datePublished\\\":\\\"2024-01-24T00:00:00.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"Ho Fung Eun\\\"}]}\"],[\"meta\",{\"property\":\"og:url\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/blog/ApacheShenYu-2.6.1.html\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"Apache ShenYu 2.6.1 Released\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"About Apache ShenYu “ official website: https://shenyu.apache.org GitHub: https://github.com/apache/shenyu Version Preview “ Version Record：https://github.com/apache/shenyu/comp...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:image\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/assets/img/blog/ApacheShenYu-2.6.1-0.png\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"en-US\"}],[\"meta\",{\"property\":\"og:locale:alternate\",\"content\":\"zh-CN\"}],[\"meta\",{\"name\":\"twitter:card\",\"content\":\"summary_large_image\"}],[\"meta\",{\"name\":\"twitter:image:src\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/assets/img/blog/ApacheShenYu-2.6.1-0.png\"}],[\"meta\",{\"name\":\"twitter:image:alt\",\"content\":\"Apache ShenYu 2.6.1 Released\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"Ho Fung Eun\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2024-01-24T00:00:00.000Z\"}],[\"link\",{\"rel\":\"alternate\",\"hreflang\":\"zh-cn\",\"href\":\"https://vuepress-theme-hope-docs-demo.netlify.app/zh/blog/ApacheShenYu-2.6.1.html\"}],[\"meta\",{\"name\":\"Blog\"}]],\"description\":\"About Apache ShenYu “ official website: https://shenyu.apache.org GitHub: https://github.com/apache/shenyu Version Preview “ Version Record：https://github.com/apache/shenyu/comp...\"},\"readingTime\":{\"minutes\":6.96,\"words\":2087},\"filePathRelative\":\"blog/ApacheShenYu-2.6.1.md\",\"autoDesc\":true}")
export { comp, data }

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
