import comp from "E:/code/newstudy/new/dromara.github.io/src/.vuepress/.temp/pages/blog/HertzBeat-v1.6.0 .html.vue"
const data = JSON.parse("{\"path\":\"/blog/HertzBeat-v1.6.0%20.html\",\"title\":\"The first Apache version v1.6.0 was released in HertzBeat!\",\"lang\":\"en-US\",\"frontmatter\":{\"title\":\"The first Apache version v1.6.0 was released in HertzBeat!\",\"author\":\"tom\",\"date\":\"2024-06-17T00:00:00.000Z\",\"cover\":\"/assets/img/blog/HertzBeat-v1.6.0-0.png\",\"head\":[[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"The first Apache version v1.6.0 was released in HertzBeat!\\\",\\\"image\\\":[\\\"https://vuepress-theme-hope-docs-demo.netlify.app/assets/img/blog/HertzBeat-v1.6.0-0.png\\\",\\\"https://vuepress-theme-hope-docs-demo.netlify.app/assets/img/blog/HertzBeat-v1.6.0-1.png\\\"],\\\"datePublished\\\":\\\"2024-06-17T00:00:00.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"tom\\\"}]}\"],[\"meta\",{\"property\":\"og:url\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/blog/HertzBeat-v1.6.0%20.html\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"The first Apache version v1.6.0 was released in HertzBeat!\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"**Hi friends, we are happy to announce that the first Apache version v1.6.0 of the Apache HertzBeat (incubating) has been released!🎉. * * After nearly 5 months of iterative com...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:image\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/assets/img/blog/HertzBeat-v1.6.0-0.png\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"en-US\"}],[\"meta\",{\"property\":\"og:locale:alternate\",\"content\":\"zh-CN\"}],[\"meta\",{\"name\":\"twitter:card\",\"content\":\"summary_large_image\"}],[\"meta\",{\"name\":\"twitter:image:src\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/assets/img/blog/HertzBeat-v1.6.0-0.png\"}],[\"meta\",{\"name\":\"twitter:image:alt\",\"content\":\"The first Apache version v1.6.0 was released in HertzBeat!\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"tom\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2024-06-17T00:00:00.000Z\"}],[\"link\",{\"rel\":\"alternate\",\"hreflang\":\"zh-cn\",\"href\":\"https://vuepress-theme-hope-docs-demo.netlify.app/zh/blog/HertzBeat-v1.6.0%20.html\"}],[\"meta\",{\"name\":\"Blog\"}]],\"description\":\"**Hi friends, we are happy to announce that the first Apache version v1.6.0 of the Apache HertzBeat (incubating) has been released!🎉. * * After nearly 5 months of iterative com...\"},\"readingTime\":{\"minutes\":13.71,\"words\":4114},\"filePathRelative\":\"blog/HertzBeat-v1.6.0 .md\",\"autoDesc\":true}")
export { comp, data }

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
