import comp from "E:/code/newstudy/new/dromara.github.io/src/.vuepress/.temp/pages/blog/hmily_introduction.html.vue"
const data = JSON.parse("{\"path\":\"/blog/hmily_introduction.html\",\"title\":\"Hmily:High-Performance Asynchronous Distributed Transaction TCC Framework\",\"lang\":\"en-US\",\"frontmatter\":{\"title\":\"Hmily:High-Performance Asynchronous Distributed Transaction TCC Framework\",\"author\":\"xiaoyu\",\"date\":\"2018-09-25T00:00:00.000Z\",\"tag\":[\"hmily\",\"TCC\"],\"cover\":\"/assets/img/architecture/hmily-framework.png\",\"head\":[[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"Hmily:High-Performance Asynchronous Distributed Transaction TCC Framework\\\",\\\"image\\\":[\\\"https://vuepress-theme-hope-docs-demo.netlify.app/assets/img/architecture/hmily-framework.png\\\"],\\\"datePublished\\\":\\\"2018-09-25T00:00:00.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"xiaoyu\\\"}]}\"],[\"meta\",{\"property\":\"og:url\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/blog/hmily_introduction.html\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"Hmily:High-Performance Asynchronous Distributed Transaction TCC Framework\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"Hmily Framework Features [https://github.com/yu199195/hmily] Seamlessly integrates with Spring and Spring Boot. Seamlessly integrates with Dubbo, Spring Cloud, Motan, and other ...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:image\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/assets/img/architecture/hmily-framework.png\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"en-US\"}],[\"meta\",{\"property\":\"og:locale:alternate\",\"content\":\"zh-CN\"}],[\"meta\",{\"name\":\"twitter:card\",\"content\":\"summary_large_image\"}],[\"meta\",{\"name\":\"twitter:image:src\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/assets/img/architecture/hmily-framework.png\"}],[\"meta\",{\"name\":\"twitter:image:alt\",\"content\":\"Hmily:High-Performance Asynchronous Distributed Transaction TCC Framework\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"xiaoyu\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"TCC\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"hmily\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2018-09-25T00:00:00.000Z\"}],[\"link\",{\"rel\":\"alternate\",\"hreflang\":\"zh-cn\",\"href\":\"https://vuepress-theme-hope-docs-demo.netlify.app/zh/blog/hmily_introduction.html\"}],[\"meta\",{\"name\":\"Blog\"}]],\"description\":\"Hmily Framework Features [https://github.com/yu199195/hmily] Seamlessly integrates with Spring and Spring Boot. Seamlessly integrates with Dubbo, Spring Cloud, Motan, and other ...\"},\"readingTime\":{\"minutes\":6.1,\"words\":1829},\"filePathRelative\":\"blog/hmily_introduction.md\",\"autoDesc\":true}")
export { comp, data }

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
