import comp from "E:/code/newstudy/new/dromara.github.io/src/.vuepress/.temp/pages/blog/LiteFlow-v2.12.1.html.vue"
const data = JSON.parse("{\"path\":\"/blog/LiteFlow-v2.12.1.html\",\"title\":\"The rule engine LiteFlow released the v2.12.1 version. How hard did it use to know\",\"lang\":\"en-US\",\"frontmatter\":{\"title\":\"The rule engine LiteFlow released the v2.12.1 version. How hard did it use to know\",\"author\":\"Platinum East\",\"date\":\"2024-06-04T00:00:00.000Z\",\"cover\":\"/assets/img/qrcode_zsxq.webp\",\"head\":[[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"The rule engine LiteFlow released the v2.12.1 version. How hard did it use to know\\\",\\\"image\\\":[\\\"https://vuepress-theme-hope-docs-demo.netlify.app/assets/img/qrcode_zsxq.webp\\\"],\\\"datePublished\\\":\\\"2024-06-04T00:00:00.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"Platinum East\\\"}]}\"],[\"meta\",{\"property\":\"og:url\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/blog/LiteFlow-v2.12.1.html\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"The rule engine LiteFlow released the v2.12.1 version. How hard did it use to know\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"\\\" LiteFlow is an open source orchestration rule engine that allows you to arrange your system logic arbitrarily, can choose script writing logic, supports up to 7 scripting lang...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:image\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/assets/img/qrcode_zsxq.webp\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"en-US\"}],[\"meta\",{\"property\":\"og:locale:alternate\",\"content\":\"zh-CN\"}],[\"meta\",{\"name\":\"twitter:card\",\"content\":\"summary_large_image\"}],[\"meta\",{\"name\":\"twitter:image:src\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/assets/img/qrcode_zsxq.webp\"}],[\"meta\",{\"name\":\"twitter:image:alt\",\"content\":\"The rule engine LiteFlow released the v2.12.1 version. How hard did it use to know\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"Platinum East\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2024-06-04T00:00:00.000Z\"}],[\"link\",{\"rel\":\"alternate\",\"hreflang\":\"zh-cn\",\"href\":\"https://vuepress-theme-hope-docs-demo.netlify.app/zh/blog/LiteFlow-v2.12.1.html\"}],[\"meta\",{\"name\":\"Blog\"}]],\"description\":\"\\\" LiteFlow is an open source orchestration rule engine that allows you to arrange your system logic arbitrarily, can choose script writing logic, supports up to 7 scripting lang...\"},\"readingTime\":{\"minutes\":3.65,\"words\":1094},\"filePathRelative\":\"blog/LiteFlow-v2.12.1.md\",\"autoDesc\":true}")
export { comp, data }

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
