import comp from "E:/code/newstudy/new/dromara.github.io/src/.vuepress/.temp/pages/blog/Sa-Token.html.vue"
const data = JSON.parse("{\"path\":\"/blog/Sa-Token.html\",\"title\":\"Commemoration:1541Days, Sa-Token Top 1 of Gitee Recommendation List\",\"lang\":\"en-US\",\"frontmatter\":{\"title\":\"Commemoration:1541Days, Sa-Token Top 1 of Gitee Recommendation List\",\"author\":\"click33\",\"date\":\"2024-04-25T00:00:00.000Z\",\"cover\":\"/assets/img/blog/Sa-Token-0.png\",\"head\":[[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"Commemoration:1541Days, Sa-Token Top 1 of Gitee Recommendation List\\\",\\\"image\\\":[\\\"https://vuepress-theme-hope-docs-demo.netlify.app/assets/img/blog/Sa-Token-0.png\\\",\\\"https://vuepress-theme-hope-docs-demo.netlify.app/assets/img/blog/Sa-Token-1.png\\\",\\\"https://vuepress-theme-hope-docs-demo.netlify.app/assets/img/blog/Sa-Token-2.png\\\"],\\\"datePublished\\\":\\\"2024-04-25T00:00:00.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"click33\\\"}]}\"],[\"meta\",{\"property\":\"og:url\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/blog/Sa-Token.html\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"Commemoration:1541Days, Sa-Token Top 1 of Gitee Recommendation List\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"2020-02-05: Submit the first version of the code. 2024-04-25: A total of 42.9k star was harvested. At this moment, it took 1541 days to reach the top of Gitee's recommendation l...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:image\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/assets/img/blog/Sa-Token-0.png\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"en-US\"}],[\"meta\",{\"property\":\"og:locale:alternate\",\"content\":\"zh-CN\"}],[\"meta\",{\"name\":\"twitter:card\",\"content\":\"summary_large_image\"}],[\"meta\",{\"name\":\"twitter:image:src\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/assets/img/blog/Sa-Token-0.png\"}],[\"meta\",{\"name\":\"twitter:image:alt\",\"content\":\"Commemoration:1541Days, Sa-Token Top 1 of Gitee Recommendation List\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"click33\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2024-04-25T00:00:00.000Z\"}],[\"link\",{\"rel\":\"alternate\",\"hreflang\":\"zh-cn\",\"href\":\"https://vuepress-theme-hope-docs-demo.netlify.app/zh/blog/Sa-Token.html\"}],[\"meta\",{\"name\":\"Blog\"}]],\"description\":\"2020-02-05: Submit the first version of the code. 2024-04-25: A total of 42.9k star was harvested. At this moment, it took 1541 days to reach the top of Gitee's recommendation l...\"},\"readingTime\":{\"minutes\":3.72,\"words\":1115},\"filePathRelative\":\"blog/Sa-Token.md\",\"autoDesc\":true}")
export { comp, data }

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
