import comp from "E:/code/newstudy/new/dromara.github.io/src/.vuepress/.temp/pages/blog/soul_source_learning_02_http_client_register.html.vue"
const data = JSON.parse("{\"path\":\"/blog/soul_source_learning_02_http_client_register.html\",\"title\":\"Soul Gateway Learning (2) HTTP Client Access Source Code Parsing\",\"lang\":\"en-US\",\"frontmatter\":{\"title\":\"Soul Gateway Learning (2) HTTP Client Access Source Code Parsing\",\"author\":\"fanjinpeng\",\"date\":\"2021-01-18T00:00:00.000Z\",\"tag\":[\"Soul\"],\"cover\":\"/assets/img/architecture/soul-framework.png\",\"head\":[[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"Soul Gateway Learning (2) HTTP Client Access Source Code Parsing\\\",\\\"image\\\":[\\\"https://vuepress-theme-hope-docs-demo.netlify.app/assets/img/architecture/soul-framework.png\\\"],\\\"datePublished\\\":\\\"2021-01-18T00:00:00.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"fanjinpeng\\\"}]}\"],[\"meta\",{\"property\":\"og:url\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/blog/soul_source_learning_02_http_client_register.html\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"Soul Gateway Learning (2) HTTP Client Access Source Code Parsing\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"Logic Analysis of HTTP User Accessing to Soul Gateway 1. Registration portal When the HTTP user accesses the Soul Gateway, it will call the soul-admin interface to register the ...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:image\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/assets/img/architecture/soul-framework.png\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"en-US\"}],[\"meta\",{\"property\":\"og:locale:alternate\",\"content\":\"zh-CN\"}],[\"meta\",{\"name\":\"twitter:card\",\"content\":\"summary_large_image\"}],[\"meta\",{\"name\":\"twitter:image:src\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/assets/img/architecture/soul-framework.png\"}],[\"meta\",{\"name\":\"twitter:image:alt\",\"content\":\"Soul Gateway Learning (2) HTTP Client Access Source Code Parsing\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"fanjinpeng\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"Soul\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2021-01-18T00:00:00.000Z\"}],[\"link\",{\"rel\":\"alternate\",\"hreflang\":\"zh-cn\",\"href\":\"https://vuepress-theme-hope-docs-demo.netlify.app/zh/blog/soul_source_learning_02_http_client_register.html\"}],[\"meta\",{\"name\":\"Blog\"}]],\"description\":\"Logic Analysis of HTTP User Accessing to Soul Gateway 1. Registration portal When the HTTP user accesses the Soul Gateway, it will call the soul-admin interface to register the ...\"},\"readingTime\":{\"minutes\":6.49,\"words\":1946},\"filePathRelative\":\"blog/soul_source_learning_02_http_client_register.md\",\"autoDesc\":true}")
export { comp, data }

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
