import comp from "E:/code/newstudy/new/dromara.github.io/src/.vuepress/.temp/pages/blog/soul_source_learning_15_plugin_chain.html.vue"
const data = JSON.parse("{\"path\":\"/blog/soul_source_learning_15_plugin_chain.html\",\"title\":\"Soul Gateway Learning Plugin Chain Implementation\",\"lang\":\"en-US\",\"frontmatter\":{\"title\":\"Soul Gateway Learning Plugin Chain Implementation\",\"author\":\"shenxiangjun\",\"date\":\"2021-01-21T00:00:00.000Z\",\"tag\":[\"Soul\"],\"cover\":\"/assets/img/blog6/mirco.png\",\"head\":[[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"Soul Gateway Learning Plugin Chain Implementation\\\",\\\"image\\\":[\\\"https://vuepress-theme-hope-docs-demo.netlify.app/assets/img/blog6/mirco.png\\\"],\\\"datePublished\\\":\\\"2021-01-21T00:00:00.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"shenxiangjun\\\"}]}\"],[\"meta\",{\"property\":\"og:url\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/blog/soul_source_learning_15_plugin_chain.html\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"Soul Gateway Learning Plugin Chain Implementation\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"I. Introduction ** Plugins are the soul of Soul. ** Soul uses the idea of plug-in design to realize the hot plug of plug-ins, and it is very easy to expand. Built-in rich plug-i...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:image\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/assets/img/blog6/mirco.png\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"en-US\"}],[\"meta\",{\"property\":\"og:locale:alternate\",\"content\":\"zh-CN\"}],[\"meta\",{\"name\":\"twitter:card\",\"content\":\"summary_large_image\"}],[\"meta\",{\"name\":\"twitter:image:src\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/assets/img/blog6/mirco.png\"}],[\"meta\",{\"name\":\"twitter:image:alt\",\"content\":\"Soul Gateway Learning Plugin Chain Implementation\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"shenxiangjun\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"Soul\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2021-01-21T00:00:00.000Z\"}],[\"link\",{\"rel\":\"alternate\",\"hreflang\":\"zh-cn\",\"href\":\"https://vuepress-theme-hope-docs-demo.netlify.app/zh/blog/soul_source_learning_15_plugin_chain.html\"}],[\"meta\",{\"name\":\"Blog\"}]],\"description\":\"I. Introduction ** Plugins are the soul of Soul. ** Soul uses the idea of plug-in design to realize the hot plug of plug-ins, and it is very easy to expand. Built-in rich plug-i...\"},\"readingTime\":{\"minutes\":0.25,\"words\":75},\"filePathRelative\":\"blog/soul_source_learning_15_plugin_chain.md\",\"autoDesc\":true}")
export { comp, data }

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
