import comp from "E:/code/newstudy/new/dromara.github.io/src/.vuepress/.temp/pages/blog/soul_source_learning_05_plugin.html.vue"
const data = JSON.parse("{\"path\":\"/blog/soul_source_learning_05_plugin.html\",\"title\":\"Soul Gateway learning plugin chain and load balancing analysis\",\"lang\":\"en-US\",\"frontmatter\":{\"title\":\"Soul Gateway learning plugin chain and load balancing analysis\",\"author\":\"zhuming\",\"date\":\"2021-01-15T00:00:00.000Z\",\"tag\":[\"Soul\"],\"cover\":\"/assets/img/architecture/soul-framework.png\",\"head\":[[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"Soul Gateway learning plugin chain and load balancing analysis\\\",\\\"image\\\":[\\\"https://vuepress-theme-hope-docs-demo.netlify.app/assets/img/01.png\\\",\\\"https://vuepress-theme-hope-docs-demo.netlify.app/assets/img/02.png\\\"],\\\"datePublished\\\":\\\"2021-01-15T00:00:00.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"zhuming\\\"}]}\"],[\"meta\",{\"property\":\"og:url\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/blog/soul_source_learning_05_plugin.html\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"Soul Gateway learning plugin chain and load balancing analysis\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"Plug-in chain summary Start with a class diagram: plugin diagramplugin diagram Two of the most basic plug-in classes are: SoulPlugin: Defines the interface of the plug-in respon...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:image\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/assets/img/architecture/soul-framework.png\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"en-US\"}],[\"meta\",{\"property\":\"og:locale:alternate\",\"content\":\"zh-CN\"}],[\"meta\",{\"name\":\"twitter:card\",\"content\":\"summary_large_image\"}],[\"meta\",{\"name\":\"twitter:image:src\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/assets/img/architecture/soul-framework.png\"}],[\"meta\",{\"name\":\"twitter:image:alt\",\"content\":\"Soul Gateway learning plugin chain and load balancing analysis\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"zhuming\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"Soul\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2021-01-15T00:00:00.000Z\"}],[\"link\",{\"rel\":\"alternate\",\"hreflang\":\"zh-cn\",\"href\":\"https://vuepress-theme-hope-docs-demo.netlify.app/zh/blog/soul_source_learning_05_plugin.html\"}],[\"meta\",{\"name\":\"Blog\"}]],\"description\":\"Plug-in chain summary Start with a class diagram: plugin diagramplugin diagram Two of the most basic plug-in classes are: SoulPlugin: Defines the interface of the plug-in respon...\"},\"readingTime\":{\"minutes\":8.96,\"words\":2689},\"filePathRelative\":\"blog/soul_source_learning_05_plugin.md\",\"autoDesc\":true}")
export { comp, data }

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
