import comp from "E:/code/newstudy/new/dromara.github.io/src/.vuepress/.temp/pages/blog/soul_source_learning_20_sentinel.html.vue"
const data = JSON.parse("{\"path\":\"/blog/soul_source_learning_20_sentinel.html\",\"title\":\"Soul Gateway Learning Sentinel Plugin\",\"lang\":\"en-US\",\"frontmatter\":{\"title\":\"Soul Gateway Learning Sentinel Plugin\",\"author\":\"luoxiaolong\",\"date\":\"2021-03-19T00:00:00.000Z\",\"tag\":[\"Soul\"],\"cover\":\"/assets/img/blog6/02.jpg\",\"head\":[[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"Soul Gateway Learning Sentinel Plugin\\\",\\\"image\\\":[\\\"https://rfc2616.oss-cn-beijing.aliyuncs.com/blog/soul16-02.png\\\",\\\"https://rfc2616.oss-cn-beijing.aliyuncs.com/blog/soul16-03.png\\\",\\\"https://rfc2616.oss-cn-beijing.aliyuncs.com/blog/soul16-04.png\\\"],\\\"datePublished\\\":\\\"2021-03-19T00:00:00.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"luoxiaolong\\\"}]}\"],[\"meta\",{\"property\":\"og:url\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/blog/soul_source_learning_20_sentinel.html\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"Soul Gateway Learning Sentinel Plugin\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"Overview Fuse and flow control are very necessary functions in the service gateway. The soul uses different mature components to implement this part of the function, and users c...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:image\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/assets/img/blog6/02.jpg\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"en-US\"}],[\"meta\",{\"property\":\"og:locale:alternate\",\"content\":\"zh-CN\"}],[\"meta\",{\"name\":\"twitter:card\",\"content\":\"summary_large_image\"}],[\"meta\",{\"name\":\"twitter:image:src\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/assets/img/blog6/02.jpg\"}],[\"meta\",{\"name\":\"twitter:image:alt\",\"content\":\"Soul Gateway Learning Sentinel Plugin\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"luoxiaolong\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"Soul\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2021-03-19T00:00:00.000Z\"}],[\"link\",{\"rel\":\"alternate\",\"hreflang\":\"zh-cn\",\"href\":\"https://vuepress-theme-hope-docs-demo.netlify.app/zh/blog/soul_source_learning_20_sentinel.html\"}],[\"meta\",{\"name\":\"Blog\"}]],\"description\":\"Overview Fuse and flow control are very necessary functions in the service gateway. The soul uses different mature components to implement this part of the function, and users c...\"},\"readingTime\":{\"minutes\":10.79,\"words\":3238},\"filePathRelative\":\"blog/soul_source_learning_20_sentinel.md\",\"autoDesc\":true}")
export { comp, data }

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
