import comp from "E:/code/newstudy/new/dromara.github.io/src/.vuepress/.temp/pages/blog/soul_source_learning_16_divide_sxj.html.vue"
const data = JSON.parse("{\"path\":\"/blog/soul_source_learning_16_divide_sxj.html\",\"title\":\"Soul Gateway Learning Divide Plugin Source Code Interpretation\",\"lang\":\"en-US\",\"frontmatter\":{\"title\":\"Soul Gateway Learning Divide Plugin Source Code Interpretation\",\"author\":\"shenxiangjun\",\"tag\":[\"Soul\"],\"date\":\"2021-02-01T00:00:00.000Z\",\"cover\":\"/assets/img/activite/soul-xmind.png\",\"head\":[[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"Soul Gateway Learning Divide Plugin Source Code Interpretation\\\",\\\"image\\\":[\\\"https://vuepress-theme-hope-docs-demo.netlify.app/assets/img/activite/soul-xmind.png\\\"],\\\"datePublished\\\":\\\"2021-02-01T00:00:00.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"shenxiangjun\\\"}]}\"],[\"meta\",{\"property\":\"og:url\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/blog/soul_source_learning_16_divide_sxj.html\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"Soul Gateway Learning Divide Plugin Source Code Interpretation\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"Plug-in overview ** Plug-in positioning ** The divide plug-in is an HTTP forward proxy plug-in, and all HTTP requests are load balanced by the plug-in (the specific load balanci...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:image\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/assets/img/activite/soul-xmind.png\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"en-US\"}],[\"meta\",{\"property\":\"og:locale:alternate\",\"content\":\"zh-CN\"}],[\"meta\",{\"name\":\"twitter:card\",\"content\":\"summary_large_image\"}],[\"meta\",{\"name\":\"twitter:image:src\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/assets/img/activite/soul-xmind.png\"}],[\"meta\",{\"name\":\"twitter:image:alt\",\"content\":\"Soul Gateway Learning Divide Plugin Source Code Interpretation\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"shenxiangjun\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"Soul\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2021-02-01T00:00:00.000Z\"}],[\"link\",{\"rel\":\"alternate\",\"hreflang\":\"zh-cn\",\"href\":\"https://vuepress-theme-hope-docs-demo.netlify.app/zh/blog/soul_source_learning_16_divide_sxj.html\"}],[\"meta\",{\"name\":\"Blog\"}]],\"description\":\"Plug-in overview ** Plug-in positioning ** The divide plug-in is an HTTP forward proxy plug-in, and all HTTP requests are load balanced by the plug-in (the specific load balanci...\"},\"readingTime\":{\"minutes\":5.26,\"words\":1579},\"filePathRelative\":\"blog/soul_source_learning_16_divide_sxj.md\",\"autoDesc\":true}")
export { comp, data }

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
