import comp from "E:/code/newstudy/new/dromara.github.io/src/.vuepress/.temp/pages/zh/activity/dromara-cloud-native-meet-02.html.vue"
const data = JSON.parse("{\"path\":\"/zh/activity/dromara-cloud-native-meet-02.html\",\"title\":\"Dromara Soul 源码01期阅读分享会02\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"Dromara Soul 源码01期阅读分享会02\",\"author\":\"xiaoyu\",\"date\":\"2021-02-06T00:00:00.000Z\",\"tag\":[\"Soul\",\"Dromara\",\"Reactor\"],\"cover\":\"/assets/img/activity/dromara-open-soul-03.jpg\",\"head\":[[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"Dromara Soul 源码01期阅读分享会02\\\",\\\"image\\\":[\\\"https://vuepress-theme-hope-docs-demo.netlify.app/assets/img/activite/soul-xmind.png\\\"],\\\"datePublished\\\":\\\"2021-02-06T00:00:00.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"xiaoyu\\\"}]}\"],[\"meta\",{\"property\":\"og:url\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/zh/activity/dromara-cloud-native-meet-02.html\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"Dromara Soul 源码01期阅读分享会02\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"Dromara 线上活动Dromara 线上活动 Dromara 源码阅读（Soul 2021 首次活动） 日期：2021 年 2 月 6 日，星期日 时间：20:00 – 23:00 地点：线上腾讯会议室 活动详情 20:00 - 20:10 开场介绍近期梦码分享情况 by kimming & 崔 20:10 - 20:25 SPI 介绍以及 Sou...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:image\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/assets/img/activity/dromara-open-soul-03.jpg\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"og:locale:alternate\",\"content\":\"en-US\"}],[\"meta\",{\"name\":\"twitter:card\",\"content\":\"summary_large_image\"}],[\"meta\",{\"name\":\"twitter:image:src\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/assets/img/activity/dromara-open-soul-03.jpg\"}],[\"meta\",{\"name\":\"twitter:image:alt\",\"content\":\"Dromara Soul 源码01期阅读分享会02\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"xiaoyu\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"Reactor\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"Dromara\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"Soul\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2021-02-06T00:00:00.000Z\"}],[\"link\",{\"rel\":\"alternate\",\"hreflang\":\"en-us\",\"href\":\"https://vuepress-theme-hope-docs-demo.netlify.app/activity/dromara-cloud-native-meet-02.html\"}],[\"meta\",{\"name\":\"活动\"}]],\"description\":\"Dromara 线上活动Dromara 线上活动 Dromara 源码阅读（Soul 2021 首次活动） 日期：2021 年 2 月 6 日，星期日 时间：20:00 – 23:00 地点：线上腾讯会议室 活动详情 20:00 - 20:10 开场介绍近期梦码分享情况 by kimming & 崔 20:10 - 20:25 SPI 介绍以及 Sou...\"},\"readingTime\":{\"minutes\":0.88,\"words\":265},\"filePathRelative\":\"zh/activity/dromara-cloud-native-meet-02.md\",\"autoDesc\":true}")
export { comp, data }

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
