import comp from "E:/code/newstudy/new/dromara.github.io/src/.vuepress/.temp/pages/zh/activity/dromara-activites-introduce.html.vue"
const data = JSON.parse("{\"path\":\"/zh/activity/dromara-activites-introduce.html\",\"title\":\"Dromara 梦码读书会介绍\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"Dromara 梦码读书会介绍\",\"author\":\"xiaoyu\",\"date\":\"2020-12-27T00:00:00.000Z\",\"tag\":[\"DreamCode\",\"Dromara\",\"GateWay\"],\"cover\":\"/assets/img/activity/dromara-open-soul-01.jpg\",\"head\":[[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"Dromara 梦码读书会介绍\\\",\\\"image\\\":[\\\"https://vuepress-theme-hope-docs-demo.netlify.app/assets/img/activite/soul-xmind.png\\\"],\\\"datePublished\\\":\\\"2020-12-27T00:00:00.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"xiaoyu\\\"}]}\"],[\"meta\",{\"property\":\"og:url\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/zh/activity/dromara-activites-introduce.html\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"Dromara 梦码读书会介绍\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"Dromara 梦码读书会介绍Dromara 梦码读书会介绍 Dromara 梦码读书会（Dromara 2020 活动介绍） 日期：2020 年 12 月 27 日，星期日 活动背景 为了提高社区参与者的积极性, 促进 Dromara 社区的建设, 锻炼大家的表达能力和提升技术核心力量, 社区以源码阅读形式自发行的组织本次活动 活动目的,意义和目标 ...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:image\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/assets/img/activity/dromara-open-soul-01.jpg\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"og:locale:alternate\",\"content\":\"en-US\"}],[\"meta\",{\"name\":\"twitter:card\",\"content\":\"summary_large_image\"}],[\"meta\",{\"name\":\"twitter:image:src\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/assets/img/activity/dromara-open-soul-01.jpg\"}],[\"meta\",{\"name\":\"twitter:image:alt\",\"content\":\"Dromara 梦码读书会介绍\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"xiaoyu\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"GateWay\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"Dromara\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"DreamCode\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2020-12-27T00:00:00.000Z\"}],[\"link\",{\"rel\":\"alternate\",\"hreflang\":\"en-us\",\"href\":\"https://vuepress-theme-hope-docs-demo.netlify.app/activity/dromara-activites-introduce.html\"}],[\"meta\",{\"name\":\"活动\"}]],\"description\":\"Dromara 梦码读书会介绍Dromara 梦码读书会介绍 Dromara 梦码读书会（Dromara 2020 活动介绍） 日期：2020 年 12 月 27 日，星期日 活动背景 为了提高社区参与者的积极性, 促进 Dromara 社区的建设, 锻炼大家的表达能力和提升技术核心力量, 社区以源码阅读形式自发行的组织本次活动 活动目的,意义和目标 ...\"},\"readingTime\":{\"minutes\":1.12,\"words\":335},\"filePathRelative\":\"zh/activity/dromara-activites-introduce.md\",\"autoDesc\":true}")
export { comp, data }

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
