import comp from "E:/code/newstudy/new/dromara.github.io/src/.vuepress/.temp/pages/zh/news/Cubic-1.4.5.html.vue"
const data = JSON.parse("{\"path\":\"/zh/news/Cubic-1.4.5.html\",\"title\":\"一站式问题定位解决平台 Cubic v1.4.5 发布\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"一站式问题定位解决平台 Cubic v1.4.5 发布\",\"author\":\"架构技术专栏\",\"date\":\"2023-05-08T00:00:00.000Z\",\"cover\":\"/assets/img/news/Cubic-1.4.5-5.png\",\"head\":[[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"一站式问题定位解决平台 Cubic v1.4.5 发布\\\",\\\"image\\\":[\\\"https://vuepress-theme-hope-docs-demo.netlify.app/assets/img/news/Cubic-1.4.5-1.png\\\",\\\"https://vuepress-theme-hope-docs-demo.netlify.app/assets/img/news/Cubic-1.4.5-2.png\\\",\\\"https://vuepress-theme-hope-docs-demo.netlify.app/assets/img/news/Cubic-1.4.5-3.png\\\",\\\"https://vuepress-theme-hope-docs-demo.netlify.app/assets/img/news/Cubic-1.4.5-4.png\\\",\\\"https://vuepress-theme-hope-docs-demo.netlify.app/assets/img/news/Cubic-1.4.5-5.png\\\",\\\"https://vuepress-theme-hope-docs-demo.netlify.app/assets/img/news/Cubic-1.4.5-6.png\\\",\\\"https://vuepress-theme-hope-docs-demo.netlify.app/assets/img/news/Cubic-1.4.5-7.png\\\",\\\"https://vuepress-theme-hope-docs-demo.netlify.app/assets/img/news/Cubic-1.4.5-8.png\\\"],\\\"datePublished\\\":\\\"2023-05-08T00:00:00.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"架构技术专栏\\\"}]}\"],[\"meta\",{\"property\":\"og:url\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/zh/news/Cubic-1.4.5.html\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"一站式问题定位解决平台 Cubic v1.4.5 发布\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"此次版本更新主要功能： 重点：新增自定义 ClassLoader,确保 agent 代码和业务代码分别由不同 Classloader 加载，避免互相污染 剥离 agent 核心代码到单独 jar 包，增强隔离性，并为插件化做准备 优化线程抓取功能的逻辑适配 欢迎大家探讨 star Gitee: https://gitee.com/dromara/cub...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:image\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/assets/img/news/Cubic-1.4.5-5.png\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"name\":\"twitter:card\",\"content\":\"summary_large_image\"}],[\"meta\",{\"name\":\"twitter:image:src\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/assets/img/news/Cubic-1.4.5-5.png\"}],[\"meta\",{\"name\":\"twitter:image:alt\",\"content\":\"一站式问题定位解决平台 Cubic v1.4.5 发布\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"架构技术专栏\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2023-05-08T00:00:00.000Z\"}],[\"meta\",{\"name\":\"新闻\"}]],\"description\":\"此次版本更新主要功能： 重点：新增自定义 ClassLoader,确保 agent 代码和业务代码分别由不同 Classloader 加载，避免互相污染 剥离 agent 核心代码到单独 jar 包，增强隔离性，并为插件化做准备 优化线程抓取功能的逻辑适配 欢迎大家探讨 star Gitee: https://gitee.com/dromara/cub...\"},\"readingTime\":{\"minutes\":0.8,\"words\":241},\"filePathRelative\":\"zh/news/Cubic-1.4.5.md\",\"autoDesc\":true}")
export { comp, data }

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
