import comp from "E:/code/newstudy/new/dromara.github.io/src/.vuepress/.temp/pages/zh/news/DomainAdmin.html.vue"
const data = JSON.parse("{\"path\":\"/zh/news/DomainAdmin.html\",\"title\":\"欢迎域名证书检测平台Domain Admin加入Dromara开源社区\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"欢迎域名证书检测平台Domain Admin加入Dromara开源社区\",\"author\":\"Domain Admin\",\"date\":\"2024-09-10T00:00:00.000Z\",\"cover\":\"/assets/img/news/DomainAdmin-0.png\",\"head\":[[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"欢迎域名证书检测平台Domain Admin加入Dromara开源社区\\\",\\\"image\\\":[\\\"https://vuepress-theme-hope-docs-demo.netlify.app/assets/img/news/DomainAdmin-0.png\\\",\\\"https://vuepress-theme-hope-docs-demo.netlify.app/assets/img/news/DomainAdmin-1.png\\\",\\\"https://vuepress-theme-hope-docs-demo.netlify.app/assets/img/news/DomainAdmin-2.png\\\",\\\"https://vuepress-theme-hope-docs-demo.netlify.app/assets/img/news/DomainAdmin-3.png\\\"],\\\"datePublished\\\":\\\"2024-09-10T00:00:00.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"Domain Admin\\\"}]}\"],[\"meta\",{\"property\":\"og:url\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/zh/news/DomainAdmin.html\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"欢迎域名证书检测平台Domain Admin加入Dromara开源社区\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"项目简介 Domain Admin是一个SSL证书申请，自动续期，到期监控工具 1、Domain Admin 采用的技术栈 后端：Python 前端：Vue3.js 2、主要功能 证书监控：统一集中式的证书监控，让你零散的网站SSL证书统一管理 证书申请：集成了Let’s Encrypt、Zero SSL免费申请SSL证书，并且支持自动续期 到期通知：...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:image\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/assets/img/news/DomainAdmin-0.png\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"og:locale:alternate\",\"content\":\"en-US\"}],[\"meta\",{\"name\":\"twitter:card\",\"content\":\"summary_large_image\"}],[\"meta\",{\"name\":\"twitter:image:src\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/assets/img/news/DomainAdmin-0.png\"}],[\"meta\",{\"name\":\"twitter:image:alt\",\"content\":\"欢迎域名证书检测平台Domain Admin加入Dromara开源社区\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"Domain Admin\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2024-09-10T00:00:00.000Z\"}],[\"link\",{\"rel\":\"alternate\",\"hreflang\":\"en-us\",\"href\":\"https://vuepress-theme-hope-docs-demo.netlify.app/news/DomainAdmin.html\"}],[\"meta\",{\"name\":\"新闻\"}]],\"description\":\"项目简介 Domain Admin是一个SSL证书申请，自动续期，到期监控工具 1、Domain Admin 采用的技术栈 后端：Python 前端：Vue3.js 2、主要功能 证书监控：统一集中式的证书监控，让你零散的网站SSL证书统一管理 证书申请：集成了Let’s Encrypt、Zero SSL免费申请SSL证书，并且支持自动续期 到期通知：...\"},\"readingTime\":{\"minutes\":0.93,\"words\":280},\"filePathRelative\":\"zh/news/DomainAdmin.md\",\"autoDesc\":true}")
export { comp, data }

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
