import comp from "E:/code/newstudy/new/dromara.github.io/src/.vuepress/.temp/pages/zh/news/fastRequest-2024.1.1.html.vue"
const data = JSON.parse("{\"path\":\"/zh/news/fastRequest-2024.1.1.html\",\"title\":\"IDEA 插件 Fast Request 2024.1.1 强势来袭\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"IDEA 插件 Fast Request 2024.1.1 强势来袭\",\"author\":\"Fast Request\",\"tag\":[\"fastRequest\"],\"date\":\"2024-01-16T00:00:00.000Z\",\"cover\":\"/assets/img/news/fastRequest-2024.1.1-0.png\",\"head\":[[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"IDEA 插件 Fast Request 2024.1.1 强势来袭\\\",\\\"image\\\":[\\\"https://vuepress-theme-hope-docs-demo.netlify.app/assets/img/news/fastRequest-2024.1.1-0.png\\\",\\\"https://vuepress-theme-hope-docs-demo.netlify.app/assets/img/news/fastRequest-2024.1.1-1.png\\\",\\\"https://vuepress-theme-hope-docs-demo.netlify.app/assets/img/news/fastRequest-2024.1.1-2.png\\\",\\\"https://vuepress-theme-hope-docs-demo.netlify.app/assets/img/news/fastRequest-2024.1.1-3.png\\\"],\\\"datePublished\\\":\\\"2024-01-16T00:00:00.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"Fast Request\\\"}]}\"],[\"meta\",{\"property\":\"og:url\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/zh/news/fastRequest-2024.1.1.html\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"IDEA 插件 Fast Request 2024.1.1 强势来袭\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"简介 Restful Fast Request 是一个类似于 Postman 的 IDEA 插件。它是一个强大的 restful api 工具包插件，可以根据已有的方法帮助您快速、自动生成 url 和 params。Restful Fast Request = API 调试工具 + API 管理工具 + API 搜索工具。它有一个漂亮的界面来完成请求、...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:image\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/assets/img/news/fastRequest-2024.1.1-0.png\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"name\":\"twitter:card\",\"content\":\"summary_large_image\"}],[\"meta\",{\"name\":\"twitter:image:src\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/assets/img/news/fastRequest-2024.1.1-0.png\"}],[\"meta\",{\"name\":\"twitter:image:alt\",\"content\":\"IDEA 插件 Fast Request 2024.1.1 强势来袭\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"Fast Request\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"fastRequest\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2024-01-16T00:00:00.000Z\"}],[\"meta\",{\"name\":\"新闻\"}]],\"description\":\"简介 Restful Fast Request 是一个类似于 Postman 的 IDEA 插件。它是一个强大的 restful api 工具包插件，可以根据已有的方法帮助您快速、自动生成 url 和 params。Restful Fast Request = API 调试工具 + API 管理工具 + API 搜索工具。它有一个漂亮的界面来完成请求、...\"},\"readingTime\":{\"minutes\":1.95,\"words\":586},\"filePathRelative\":\"zh/news/fastRequest-2024.1.1.md\",\"autoDesc\":true}")
export { comp, data }

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
