import comp from "E:/code/newstudy/new/dromara.github.io/src/.vuepress/.temp/pages/zh/news/HertzBeat-1.4.1.html.vue"
const data = JSON.parse("{\"path\":\"/zh/news/HertzBeat-1.4.1.html\",\"title\":\"更好的用户体验, 开源实时监控 HertzBeat 新版发布\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"更好的用户体验, 开源实时监控 HertzBeat 新版发布\",\"author\":\"tom\",\"tag\":[\"HertzBeat\"],\"date\":\"2023-09-27T00:00:00.000Z\",\"cover\":\"/assets/img/news/HertzBeat-1.4.1-1.png\",\"head\":[[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"更好的用户体验, 开源实时监控 HertzBeat 新版发布\\\",\\\"image\\\":[\\\"https://vuepress-theme-hope-docs-demo.netlify.app/assets/img/news/HertzBeat-1.4.1-1.png\\\",\\\"https://vuepress-theme-hope-docs-demo.netlify.app/assets/img/news/HertzBeat-1.4.1-2.png\\\",\\\"https://vuepress-theme-hope-docs-demo.netlify.app/assets/img/news/HertzBeat-1.4.1-3.png\\\",\\\"https://vuepress-theme-hope-docs-demo.netlify.app/assets/img/news/HertzBeat-1.4.1-4.png\\\",\\\"https://vuepress-theme-hope-docs-demo.netlify.app/assets/img/news/HertzBeat-1.4.1-5.png\\\",\\\"https://vuepress-theme-hope-docs-demo.netlify.app/assets/img/news/HertzBeat-1.4.1-6.png\\\",\\\"https://vuepress-theme-hope-docs-demo.netlify.app/assets/img/news/HertzBeat-1.4.1-7.png\\\"],\\\"datePublished\\\":\\\"2023-09-27T00:00:00.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"tom\\\"}]}\"],[\"meta\",{\"property\":\"og:url\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/zh/news/HertzBeat-1.4.1.html\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"更好的用户体验, 开源实时监控 HertzBeat 新版发布\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"哈喽大家好，时间很快 1 个多月又过去了，HertzBeat 经过近两个月的迭代终于发布了 v1.4.1 版本。为什么是终于，因为有点难哈哈。我们参考 rocketmq 重构了 netty 的 server client 端模块，重构了采集器集群调度。比起上一版本有了更优雅的通讯代码，更完善全面的集群。采集任务一致性 hash 调度，集群心跳保活，断开...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:image\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/assets/img/news/HertzBeat-1.4.1-1.png\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"name\":\"twitter:card\",\"content\":\"summary_large_image\"}],[\"meta\",{\"name\":\"twitter:image:src\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/assets/img/news/HertzBeat-1.4.1-1.png\"}],[\"meta\",{\"name\":\"twitter:image:alt\",\"content\":\"更好的用户体验, 开源实时监控 HertzBeat 新版发布\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"tom\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"HertzBeat\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2023-09-27T00:00:00.000Z\"}],[\"meta\",{\"name\":\"新闻\"}]],\"description\":\"哈喽大家好，时间很快 1 个多月又过去了，HertzBeat 经过近两个月的迭代终于发布了 v1.4.1 版本。为什么是终于，因为有点难哈哈。我们参考 rocketmq 重构了 netty 的 server client 端模块，重构了采集器集群调度。比起上一版本有了更优雅的通讯代码，更完善全面的集群。采集任务一致性 hash 调度，集群心跳保活，断开...\"},\"readingTime\":{\"minutes\":3.22,\"words\":965},\"filePathRelative\":\"zh/news/HertzBeat-1.4.1.md\",\"autoDesc\":true}")
export { comp, data }

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
