import comp from "E:/code/newstudy/new/dromara.github.io/src/.vuepress/.temp/pages/zh/news/HertzBeat-1.5.0.html.vue"
const data = JSON.parse("{\"path\":\"/zh/news/HertzBeat-1.5.0.html\",\"title\":\"赫兹跳动 v1.5.0 发布，新增强大 Status Page 构建能力\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"赫兹跳动 v1.5.0 发布，新增强大 Status Page 构建能力\",\"author\":\"tom\",\"tag\":[\"HertzBeat\"],\"date\":\"2024-02-08T00:00:00.000Z\",\"cover\":\"/assets/img/news/HertzBeat-1.5.0-0.png\",\"head\":[[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"赫兹跳动 v1.5.0 发布，新增强大 Status Page 构建能力\\\",\\\"image\\\":[\\\"https://vuepress-theme-hope-docs-demo.netlify.app/assets/img/news/HertzBeat-1.5.0-0.png\\\",\\\"https://vuepress-theme-hope-docs-demo.netlify.app/assets/img/news/HertzBeat-1.5.0-1.png\\\",\\\"https://vuepress-theme-hope-docs-demo.netlify.app/assets/img/news/HertzBeat-1.5.0-2.png\\\",\\\"https://vuepress-theme-hope-docs-demo.netlify.app/assets/img/news/HertzBeat-1.5.0-3.png\\\",\\\"https://vuepress-theme-hope-docs-demo.netlify.app/assets/img/news/HertzBeat-1.5.0-4.png\\\"],\\\"datePublished\\\":\\\"2024-02-08T00:00:00.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"tom\\\"}]}\"],[\"meta\",{\"property\":\"og:url\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/zh/news/HertzBeat-1.5.0.html\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"赫兹跳动 v1.5.0 发布，新增强大 Status Page 构建能力\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"新年好呀 没想到在除夕之前还能出一个版本，HertzBeat v1.5.0 发布啦，刚好一月一版。 这个版本我们主要是新提供了 Status Page 状态页面构建功能，用户可以通过赫兹跳动构建自己团队服务的对外状态页面，支持状态页状态与监控实例状态联动，支持发布维护异常事件。 通过 Status Page 轻松向用户传达您产品服务的实时状态 如果你们...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:image\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/assets/img/news/HertzBeat-1.5.0-0.png\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"name\":\"twitter:card\",\"content\":\"summary_large_image\"}],[\"meta\",{\"name\":\"twitter:image:src\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/assets/img/news/HertzBeat-1.5.0-0.png\"}],[\"meta\",{\"name\":\"twitter:image:alt\",\"content\":\"赫兹跳动 v1.5.0 发布，新增强大 Status Page 构建能力\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"tom\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"HertzBeat\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2024-02-08T00:00:00.000Z\"}],[\"meta\",{\"name\":\"新闻\"}]],\"description\":\"新年好呀 没想到在除夕之前还能出一个版本，HertzBeat v1.5.0 发布啦，刚好一月一版。 这个版本我们主要是新提供了 Status Page 状态页面构建功能，用户可以通过赫兹跳动构建自己团队服务的对外状态页面，支持状态页状态与监控实例状态联动，支持发布维护异常事件。 通过 Status Page 轻松向用户传达您产品服务的实时状态 如果你们...\"},\"readingTime\":{\"minutes\":2.49,\"words\":748},\"filePathRelative\":\"zh/news/HertzBeat-1.5.0.md\",\"autoDesc\":true}")
export { comp, data }

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
