import comp from "E:/code/newstudy/new/dromara.github.io/src/.vuepress/.temp/pages/zh/news/MybatisPlusExt.html.vue"
const data = JSON.parse("{\"path\":\"/zh/news/MybatisPlusExt.html\",\"title\":\"欢迎新晋开源MPE加入Dromara社区，MybatisPlus能力拓展增强包\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"欢迎新晋开源MPE加入Dromara社区，MybatisPlus能力拓展增强包\",\"author\":\"MybatisPlusExt\",\"date\":\"2024-03-11T00:00:00.000Z\",\"cover\":\"/assets/img/news/MybatisPlusExt-0.png\",\"head\":[[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"欢迎新晋开源MPE加入Dromara社区，MybatisPlus能力拓展增强包\\\",\\\"image\\\":[\\\"https://vuepress-theme-hope-docs-demo.netlify.app/assets/img/news/MybatisPlusExt-0.png\\\",\\\"https://vuepress-theme-hope-docs-demo.netlify.app/assets/img/news/MybatisPlusExt-1.png\\\",\\\"https://vuepress-theme-hope-docs-demo.netlify.app/assets/img/news/MybatisPlusExt-2.png\\\"],\\\"datePublished\\\":\\\"2024-03-11T00:00:00.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"MybatisPlusExt\\\"}]}\"],[\"meta\",{\"property\":\"og:url\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/zh/news/MybatisPlusExt.html\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"欢迎新晋开源MPE加入Dromara社区，MybatisPlus能力拓展增强包\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"借用MybatisPlus的口号：为简化开发工作、提高生产率而生 尽管MybatisPlus （后文简称MP）相比较Mybatis丝滑了很多，但是日常使用中，是否偶尔仍会怀念JPA（Hibernate）的那种纵享丝滑的感受，更好的一心投入业务开发中，如果你也是如此，那么恭喜你发现了MybatisPlusExt（后文简称MPE）。 MPE对MP做了进一步...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:image\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/assets/img/news/MybatisPlusExt-0.png\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"og:locale:alternate\",\"content\":\"en-US\"}],[\"meta\",{\"name\":\"twitter:card\",\"content\":\"summary_large_image\"}],[\"meta\",{\"name\":\"twitter:image:src\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/assets/img/news/MybatisPlusExt-0.png\"}],[\"meta\",{\"name\":\"twitter:image:alt\",\"content\":\"欢迎新晋开源MPE加入Dromara社区，MybatisPlus能力拓展增强包\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"MybatisPlusExt\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2024-03-11T00:00:00.000Z\"}],[\"link\",{\"rel\":\"alternate\",\"hreflang\":\"en-us\",\"href\":\"https://vuepress-theme-hope-docs-demo.netlify.app/news/MybatisPlusExt.html\"}],[\"meta\",{\"name\":\"新闻\"}]],\"description\":\"借用MybatisPlus的口号：为简化开发工作、提高生产率而生 尽管MybatisPlus （后文简称MP）相比较Mybatis丝滑了很多，但是日常使用中，是否偶尔仍会怀念JPA（Hibernate）的那种纵享丝滑的感受，更好的一心投入业务开发中，如果你也是如此，那么恭喜你发现了MybatisPlusExt（后文简称MPE）。 MPE对MP做了进一步...\"},\"readingTime\":{\"minutes\":13.59,\"words\":4077},\"filePathRelative\":\"zh/news/MybatisPlusExt.md\",\"autoDesc\":true}")
export { comp, data }

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
