import comp from "E:/code/newstudy/new/dromara.github.io/src/.vuepress/.temp/pages/zh/news/Skyeye-3.14.3.html.vue"
const data = JSON.parse("{\"path\":\"/zh/news/Skyeye-3.14.3.html\",\"title\":\"智能制造 v3.14.3 发布\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"智能制造 v3.14.3 发布\",\"author\":\"卫志强\",\"tag\":[\"Skyeye\"],\"date\":\"2024-09-04T00:00:00.000Z\",\"cover\":\"/assets/img/news/Skyeye-3.14.3-0.webp\",\"head\":[[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"智能制造 v3.14.3 发布\\\",\\\"image\\\":[\\\"https://vuepress-theme-hope-docs-demo.netlify.app/assets/img/news/Skyeye-3.14.3-0.webp\\\",\\\"https://vuepress-theme-hope-docs-demo.netlify.app/assets/img/news/Skyeye-3.14.3-1.webp\\\",\\\"https://vuepress-theme-hope-docs-demo.netlify.app/assets/img/news/Skyeye-3.14.3-2.webp\\\",\\\"https://vuepress-theme-hope-docs-demo.netlify.app/assets/img/news/Skyeye-3.14.3-3.webp\\\"],\\\"datePublished\\\":\\\"2024-09-04T00:00:00.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"卫志强\\\"}]}\"],[\"meta\",{\"property\":\"og:url\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/zh/news/Skyeye-3.14.3.html\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"智能制造 v3.14.3 发布\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"智能制造一体化管理系统 [SpringBoot2 - 快速开发平台]，适用于制造业、建筑业、汽车行业、互联网、教育、政府机关等机构的管理。包含文件在线操作、工作日志、多班次考勤、CRM、ERP 进销存、项目管理、EHR、拖拽式生成问卷、日程、笔记、工作计划、行政办公、薪资模块、动态表单、知识库、公告模块、企业论坛、云售后模块、生产模块、系统模块化同步模...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:image\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/assets/img/news/Skyeye-3.14.3-0.webp\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"og:locale:alternate\",\"content\":\"en-US\"}],[\"meta\",{\"name\":\"twitter:card\",\"content\":\"summary_large_image\"}],[\"meta\",{\"name\":\"twitter:image:src\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/assets/img/news/Skyeye-3.14.3-0.webp\"}],[\"meta\",{\"name\":\"twitter:image:alt\",\"content\":\"智能制造 v3.14.3 发布\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"卫志强\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"Skyeye\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2024-09-04T00:00:00.000Z\"}],[\"link\",{\"rel\":\"alternate\",\"hreflang\":\"en-us\",\"href\":\"https://vuepress-theme-hope-docs-demo.netlify.app/news/Skyeye-3.14.3.html\"}],[\"meta\",{\"name\":\"新闻\"}]],\"description\":\"智能制造一体化管理系统 [SpringBoot2 - 快速开发平台]，适用于制造业、建筑业、汽车行业、互联网、教育、政府机关等机构的管理。包含文件在线操作、工作日志、多班次考勤、CRM、ERP 进销存、项目管理、EHR、拖拽式生成问卷、日程、笔记、工作计划、行政办公、薪资模块、动态表单、知识库、公告模块、企业论坛、云售后模块、生产模块、系统模块化同步模...\"},\"readingTime\":{\"minutes\":1.82,\"words\":546},\"filePathRelative\":\"zh/news/Skyeye-3.14.3.md\",\"autoDesc\":true}")
export { comp, data }

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
