import comp from "E:/code/newstudy/new/dromara.github.io/src/.vuepress/.temp/pages/zh/news/soul-2.1.x.html.vue"
const data = JSON.parse("{\"path\":\"/zh/news/soul-2.1.x.html\",\"title\":\"Soul网关发布的2.1.X版本，到底有多方便？\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"Soul网关发布的2.1.X版本，到底有多方便？\",\"author\":\"xiaoyu\",\"tag\":[\"Soul\"],\"date\":\"2019-12-12T00:00:00.000Z\",\"cover\":\"/assets/img/architecture/soul-framework.png\",\"head\":[[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"Soul网关发布的2.1.X版本，到底有多方便？\\\",\\\"image\\\":[\\\"https://vuepress-theme-hope-docs-demo.netlify.app/assets/img/architecture/soul-rpc.png\\\",\\\"https://vuepress-theme-hope-docs-demo.netlify.app/assets/img/architecture/soul-admin-1.png\\\",\\\"https://vuepress-theme-hope-docs-demo.netlify.app/assets/img/architecture/soul-framework.png\\\"],\\\"datePublished\\\":\\\"2019-12-12T00:00:00.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"xiaoyu\\\"}]}\"],[\"meta\",{\"property\":\"og:url\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/zh/news/soul-2.1.x.html\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"Soul网关发布的2.1.X版本，到底有多方便？\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"Soul 网关自从去年 10 月我开源以来，经历了一年的事情，接受到了来自社区很多朋友的建议，并进行持续不断的优化，已经提供了非常丰富的功能，很多功能都是高度自定义，可视化，高度可扩展的，现在做一个归纳总结。 插件 提供了系统自带的各种插件，比如签名，监控，限流，熔断，http 代理，dubbo 代理，websocket 等等。 支持用户快速的进行插件...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:image\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/assets/img/architecture/soul-framework.png\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"og:locale:alternate\",\"content\":\"en-US\"}],[\"meta\",{\"name\":\"twitter:card\",\"content\":\"summary_large_image\"}],[\"meta\",{\"name\":\"twitter:image:src\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/assets/img/architecture/soul-framework.png\"}],[\"meta\",{\"name\":\"twitter:image:alt\",\"content\":\"Soul网关发布的2.1.X版本，到底有多方便？\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"xiaoyu\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"Soul\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2019-12-12T00:00:00.000Z\"}],[\"link\",{\"rel\":\"alternate\",\"hreflang\":\"en-us\",\"href\":\"https://vuepress-theme-hope-docs-demo.netlify.app/news/soul-2.1.x.html\"}],[\"meta\",{\"name\":\"新闻\"}]],\"description\":\"Soul 网关自从去年 10 月我开源以来，经历了一年的事情，接受到了来自社区很多朋友的建议，并进行持续不断的优化，已经提供了非常丰富的功能，很多功能都是高度自定义，可视化，高度可扩展的，现在做一个归纳总结。 插件 提供了系统自带的各种插件，比如签名，监控，限流，熔断，http 代理，dubbo 代理，websocket 等等。 支持用户快速的进行插件...\"},\"readingTime\":{\"minutes\":5.08,\"words\":1524},\"filePathRelative\":\"zh/news/soul-2.1.x.md\",\"autoDesc\":true}")
export { comp, data }

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
