import comp from "E:/code/newstudy/new/dromara.github.io/src/.vuepress/.temp/pages/zh/news/zyplayer-doc-1.1.6.html.vue"
const data = JSON.parse("{\"path\":\"/zh/news/zyplayer-doc-1.1.6.html\",\"title\":\"zyplayer-doc 1.1.6-Release\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"zyplayer-doc 1.1.6-Release\",\"author\":\"zyplayer\",\"tag\":[\"zyplayer-doc\"],\"date\":\"2023-10-16T00:00:00.000Z\",\"cover\":\"/assets/img/logo/zyplayer-doc.webp\",\"head\":[[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"zyplayer-doc 1.1.6-Release\\\",\\\"image\\\":[\\\"https://vuepress-theme-hope-docs-demo.netlify.app/assets/img/news/zyplayer-1-1-6-1.png\\\",\\\"https://vuepress-theme-hope-docs-demo.netlify.app/assets/img/news/zyplayer-1-1-6-2.png\\\",\\\"https://vuepress-theme-hope-docs-demo.netlify.app/assets/img/news/zyplayer-1-1-6-3.png\\\"],\\\"datePublished\\\":\\\"2023-10-16T00:00:00.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"zyplayer\\\"}]}\"],[\"meta\",{\"property\":\"og:url\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/zh/news/zyplayer-doc-1.1.6.html\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"zyplayer-doc 1.1.6-Release\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"简介 zyplayer-doc是一款适合企业和个人私有化部署使用的 WIKI 知识库管理系统，提供在线化的知识库管理功能，专为私有化部署而设计，最大程度上保证企业或个人的数据安全。 可用于企业内部协作的知识库、规章制度，企业对外的产品帮助文档，个人笔记、WIKI 知识库等场景使用。 提供有富文本和 Markdown 格式的编辑器，具有附件、评论和历史版...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:image\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/assets/img/logo/zyplayer-doc.webp\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"og:locale:alternate\",\"content\":\"en-US\"}],[\"meta\",{\"name\":\"twitter:card\",\"content\":\"summary_large_image\"}],[\"meta\",{\"name\":\"twitter:image:src\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/assets/img/logo/zyplayer-doc.webp\"}],[\"meta\",{\"name\":\"twitter:image:alt\",\"content\":\"zyplayer-doc 1.1.6-Release\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"zyplayer\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"zyplayer-doc\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2023-10-16T00:00:00.000Z\"}],[\"link\",{\"rel\":\"alternate\",\"hreflang\":\"en-us\",\"href\":\"https://vuepress-theme-hope-docs-demo.netlify.app/news/zyplayer-doc-1.1.6.html\"}],[\"meta\",{\"name\":\"新闻\"}]],\"description\":\"简介 zyplayer-doc是一款适合企业和个人私有化部署使用的 WIKI 知识库管理系统，提供在线化的知识库管理功能，专为私有化部署而设计，最大程度上保证企业或个人的数据安全。 可用于企业内部协作的知识库、规章制度，企业对外的产品帮助文档，个人笔记、WIKI 知识库等场景使用。 提供有富文本和 Markdown 格式的编辑器，具有附件、评论和历史版...\"},\"readingTime\":{\"minutes\":1.85,\"words\":556},\"filePathRelative\":\"zh/news/zyplayer-doc-1.1.6.md\",\"autoDesc\":true}")
export { comp, data }

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
