import comp from "E:/code/newstudy/new/dromara.github.io/src/.vuepress/.temp/pages/news/DromaraDaxPay.html.vue"
const data = JSON.parse("{\"path\":\"/news/DromaraDaxPay.html\",\"title\":\"Welcome to the new open source payment gateway，Dromara DaxPay\",\"lang\":\"en-US\",\"frontmatter\":{\"title\":\"Welcome to the new open source payment gateway，Dromara DaxPay\",\"author\":\"喵呀\",\"date\":\"2024-02-26T00:00:00.000Z\",\"cover\":\"/assets/img/news/Dromara-DaxPay-0.png\",\"head\":[[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"Welcome to the new open source payment gateway，Dromara DaxPay\\\",\\\"image\\\":[\\\"https://vuepress-theme-hope-docs-demo.netlify.app/assets/img/news/Dromara-DaxPay-0.png\\\",\\\"https://vuepress-theme-hope-docs-demo.netlify.app/assets/img/news/Dromara-DaxPay-1.png\\\",\\\"https://vuepress-theme-hope-docs-demo.netlify.app/assets/img/news/Dromara-DaxPay-2.png\\\",\\\"https://vuepress-theme-hope-docs-demo.netlify.app/assets/img/news/Dromara-DaxPay-3.png\\\"],\\\"datePublished\\\":\\\"2024-02-26T00:00:00.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"喵呀\\\"}]}\"],[\"meta\",{\"property\":\"og:url\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/news/DromaraDaxPay.html\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"Welcome to the new open source payment gateway，Dromara DaxPay\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"Author introduction Name: Meow dromara open source organization member, dromara/dax-pay author Payment industry recruits, Java senior development engineer, development, design, ...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:image\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/assets/img/news/Dromara-DaxPay-0.png\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"en-US\"}],[\"meta\",{\"property\":\"og:locale:alternate\",\"content\":\"zh-CN\"}],[\"meta\",{\"name\":\"twitter:card\",\"content\":\"summary_large_image\"}],[\"meta\",{\"name\":\"twitter:image:src\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/assets/img/news/Dromara-DaxPay-0.png\"}],[\"meta\",{\"name\":\"twitter:image:alt\",\"content\":\"Welcome to the new open source payment gateway，Dromara DaxPay\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"喵呀\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2024-02-26T00:00:00.000Z\"}],[\"link\",{\"rel\":\"alternate\",\"hreflang\":\"zh-cn\",\"href\":\"https://vuepress-theme-hope-docs-demo.netlify.app/zh/news/DromaraDaxPay.html\"}],[\"meta\",{\"name\":\"News\"}]],\"description\":\"Author introduction Name: Meow dromara open source organization member, dromara/dax-pay author Payment industry recruits, Java senior development engineer, development, design, ...\"},\"readingTime\":{\"minutes\":3.74,\"words\":1121},\"filePathRelative\":\"news/DromaraDaxPay.md\",\"autoDesc\":true}")
export { comp, data }

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
