import comp from "E:/code/newstudy/new/dromara.github.io/src/.vuepress/.temp/pages/news/easyAI-1.1.7.html.vue"
const data = JSON.parse("{\"path\":\"/news/easyAI-1.1.7.html\",\"title\":\"easyAI v1.1.7 New version released, Java native AI algorithm development engine\",\"lang\":\"en-US\",\"frontmatter\":{\"title\":\"easyAI v1.1.7 New version released, Java native AI algorithm development engine\",\"author\":\"easyAI\",\"tag\":[\"EasyAI\"],\"date\":\"2024-03-04T00:00:00.000Z\",\"cover\":\"/assets/img/news/easyAI-1.1.7-0.png\",\"head\":[[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"easyAI v1.1.7 New version released, Java native AI algorithm development engine\\\",\\\"image\\\":[\\\"https://vuepress-theme-hope-docs-demo.netlify.app/assets/img/news/easyAI-1.1.7-0.png\\\",\\\"https://vuepress-theme-hope-docs-demo.netlify.app/assets/img/news/easyAI-1.1.7-5.png\\\"],\\\"datePublished\\\":\\\"2024-03-04T00:00:00.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"easyAI\\\"}]}\"],[\"meta\",{\"property\":\"og:url\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/news/easyAI-1.1.7.html\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"easyAI v1.1.7 New version released, Java native AI algorithm development engine\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"Introduction easyAI is the 1 java pure native AI algorithm development engine, built-in a variety of machine learning, reinforcement learning, evolutionary learning and a variet...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:image\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/assets/img/news/easyAI-1.1.7-0.png\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"en-US\"}],[\"meta\",{\"property\":\"og:locale:alternate\",\"content\":\"zh-CN\"}],[\"meta\",{\"name\":\"twitter:card\",\"content\":\"summary_large_image\"}],[\"meta\",{\"name\":\"twitter:image:src\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/assets/img/news/easyAI-1.1.7-0.png\"}],[\"meta\",{\"name\":\"twitter:image:alt\",\"content\":\"easyAI v1.1.7 New version released, Java native AI algorithm development engine\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"easyAI\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"EasyAI\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2024-03-04T00:00:00.000Z\"}],[\"link\",{\"rel\":\"alternate\",\"hreflang\":\"zh-cn\",\"href\":\"https://vuepress-theme-hope-docs-demo.netlify.app/zh/news/easyAI-1.1.7.html\"}],[\"meta\",{\"name\":\"News\"}]],\"description\":\"Introduction easyAI is the 1 java pure native AI algorithm development engine, built-in a variety of machine learning, reinforcement learning, evolutionary learning and a variet...\"},\"readingTime\":{\"minutes\":2.73,\"words\":820},\"filePathRelative\":\"news/easyAI-1.1.7.md\",\"autoDesc\":true}")
export { comp, data }

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
