import comp from "E:/code/newstudy/new/dromara.github.io/src/.vuepress/.temp/pages/news/hmily-restart.html.vue"
const data = JSON.parse("{\"path\":\"/news/hmily-restart.html\",\"title\":\"Hmily distributed transaction restart monthly report\",\"lang\":\"en-US\",\"frontmatter\":{\"title\":\"Hmily distributed transaction restart monthly report\",\"author\":\"xiaoyu\",\"date\":\"2020-09-08T00:00:00.000Z\",\"tag\":[\"hmily\"],\"cover\":\"/assets/img/architecture/hmily-framework.png\",\"head\":[[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"Hmily distributed transaction restart monthly report\\\",\\\"image\\\":[\\\"https://vuepress-theme-hope-docs-demo.netlify.app/assets/img/architecture/hmily-framework.png\\\",\\\"https://vuepress-theme-hope-docs-demo.netlify.app/assets/img/architecture/hmily-bug.png\\\"],\\\"datePublished\\\":\\\"2020-09-08T00:00:00.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"xiaoyu\\\"}]}\"],[\"meta\",{\"property\":\"og:url\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/news/hmily-restart.html\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"Hmily distributed transaction restart monthly report\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"Hmily is a flexible distributed transaction architecture with high performance, high avalibility and ease to use. At present, it provides support for Dubbo, Spring-Cloud, Motan,...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:image\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/assets/img/architecture/hmily-framework.png\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"en-US\"}],[\"meta\",{\"property\":\"og:locale:alternate\",\"content\":\"zh-CN\"}],[\"meta\",{\"name\":\"twitter:card\",\"content\":\"summary_large_image\"}],[\"meta\",{\"name\":\"twitter:image:src\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/assets/img/architecture/hmily-framework.png\"}],[\"meta\",{\"name\":\"twitter:image:alt\",\"content\":\"Hmily distributed transaction restart monthly report\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"xiaoyu\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"hmily\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2020-09-08T00:00:00.000Z\"}],[\"link\",{\"rel\":\"alternate\",\"hreflang\":\"zh-cn\",\"href\":\"https://vuepress-theme-hope-docs-demo.netlify.app/zh/news/hmily-restart.html\"}],[\"meta\",{\"name\":\"News\"}]],\"description\":\"Hmily is a flexible distributed transaction architecture with high performance, high avalibility and ease to use. At present, it provides support for Dubbo, Spring-Cloud, Motan,...\"},\"readingTime\":{\"minutes\":1.84,\"words\":551},\"filePathRelative\":\"news/hmily-restart.md\",\"autoDesc\":true}")
export { comp, data }

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
