import comp from "E:/code/newstudy/new/dromara.github.io/src/.vuepress/.temp/pages/news/MaxKey-4.1.1.html.vue"
const data = JSON.parse("{\"path\":\"/news/MaxKey-4.1.1.html\",\"title\":\"MaxKey single sign-on authentication system 4.1.1,APP scan code login\",\"lang\":\"en-US\",\"frontmatter\":{\"title\":\"MaxKey single sign-on authentication system 4.1.1,APP scan code login\",\"author\":\"maxkey\",\"date\":\"2024-08-22T00:00:00.000Z\",\"cover\":\"/assets/img/news/MaxKey-4.1.1-0.png\",\"head\":[[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"MaxKey single sign-on authentication system 4.1.1,APP scan code login\\\",\\\"image\\\":[\\\"https://vuepress-theme-hope-docs-demo.netlify.app/assets/img/news/MaxKey-4.1.1-0.png\\\",\\\"https://vuepress-theme-hope-docs-demo.netlify.app/assets/img/news/MaxKey-4.1.1-1.png\\\",\\\"https://vuepress-theme-hope-docs-demo.netlify.app/assets/img/qrcode_zsxq.webp\\\"],\\\"datePublished\\\":\\\"2024-08-22T00:00:00.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"maxkey\\\"}]}\"],[\"meta\",{\"property\":\"og:url\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/news/MaxKey-4.1.1.html\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"MaxKey single sign-on authentication system 4.1.1,APP scan code login\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"Industry-leading IAM-IDaas identity management and authentication products Overview MaxKey single sign-on authentication system, homophonic Marx's key implies the largest key, i...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:image\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/assets/img/news/MaxKey-4.1.1-0.png\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"en-US\"}],[\"meta\",{\"property\":\"og:locale:alternate\",\"content\":\"zh-CN\"}],[\"meta\",{\"name\":\"twitter:card\",\"content\":\"summary_large_image\"}],[\"meta\",{\"name\":\"twitter:image:src\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/assets/img/news/MaxKey-4.1.1-0.png\"}],[\"meta\",{\"name\":\"twitter:image:alt\",\"content\":\"MaxKey single sign-on authentication system 4.1.1,APP scan code login\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"maxkey\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2024-08-22T00:00:00.000Z\"}],[\"link\",{\"rel\":\"alternate\",\"hreflang\":\"zh-cn\",\"href\":\"https://vuepress-theme-hope-docs-demo.netlify.app/zh/news/MaxKey-4.1.1.html\"}],[\"meta\",{\"name\":\"News\"}]],\"description\":\"Industry-leading IAM-IDaas identity management and authentication products Overview MaxKey single sign-on authentication system, homophonic Marx's key implies the largest key, i...\"},\"readingTime\":{\"minutes\":2.23,\"words\":669},\"filePathRelative\":\"news/MaxKey-4.1.1.md\",\"autoDesc\":true}")
export { comp, data }

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
