import comp from "E:/code/newstudy/new/dromara.github.io/src/.vuepress/.temp/pages/news/Skyeye-3.14.3.html.vue"
const data = JSON.parse("{\"path\":\"/news/Skyeye-3.14.3.html\",\"title\":\"Smart Manufacturing v3.14.3 Released\",\"lang\":\"en-US\",\"frontmatter\":{\"title\":\"Smart Manufacturing v3.14.3 Released\",\"author\":\"Wei Zhiqiang\",\"tag\":[\"Skyeye\"],\"date\":\"2024-09-04T00:00:00.000Z\",\"cover\":\"/assets/img/news/Skyeye-3.14.3-0.webp\",\"head\":[[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"Smart Manufacturing v3.14.3 Released\\\",\\\"image\\\":[\\\"https://vuepress-theme-hope-docs-demo.netlify.app/assets/img/news/Skyeye-3.14.3-0.webp\\\",\\\"https://vuepress-theme-hope-docs-demo.netlify.app/assets/img/news/Skyeye-3.14.3-1.webp\\\",\\\"https://vuepress-theme-hope-docs-demo.netlify.app/assets/img/news/Skyeye-3.14.3-2.webp\\\",\\\"https://vuepress-theme-hope-docs-demo.netlify.app/assets/img/news/Skyeye-3.14.3-3.webp\\\"],\\\"datePublished\\\":\\\"2024-09-04T00:00:00.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"Wei Zhiqiang\\\"}]}\"],[\"meta\",{\"property\":\"og:url\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/news/Skyeye-3.14.3.html\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"Smart Manufacturing v3.14.3 Released\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"Intelligent manufacturing integrated management system [SpringBoot2-rapid development platform ], suitable for the management of manufacturing, construction, automobile industry...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:image\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/assets/img/news/Skyeye-3.14.3-0.webp\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"en-US\"}],[\"meta\",{\"property\":\"og:locale:alternate\",\"content\":\"zh-CN\"}],[\"meta\",{\"name\":\"twitter:card\",\"content\":\"summary_large_image\"}],[\"meta\",{\"name\":\"twitter:image:src\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/assets/img/news/Skyeye-3.14.3-0.webp\"}],[\"meta\",{\"name\":\"twitter:image:alt\",\"content\":\"Smart Manufacturing v3.14.3 Released\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"Wei Zhiqiang\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"Skyeye\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2024-09-04T00:00:00.000Z\"}],[\"link\",{\"rel\":\"alternate\",\"hreflang\":\"zh-cn\",\"href\":\"https://vuepress-theme-hope-docs-demo.netlify.app/zh/news/Skyeye-3.14.3.html\"}],[\"meta\",{\"name\":\"News\"}]],\"description\":\"Intelligent manufacturing integrated management system [SpringBoot2-rapid development platform ], suitable for the management of manufacturing, construction, automobile industry...\"},\"readingTime\":{\"minutes\":1.29,\"words\":388},\"filePathRelative\":\"news/Skyeye-3.14.3.md\",\"autoDesc\":true}")
export { comp, data }

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
