import comp from "E:/code/newstudy/new/dromara.github.io/src/.vuepress/.temp/pages/news/Skyeye-3.14.4.html.vue"
const data = JSON.parse("{\"path\":\"/news/Skyeye-3.14.4.html\",\"title\":\"Intelligent manufacturing v3.14.4 release, ERP mall\",\"lang\":\"en-US\",\"frontmatter\":{\"title\":\"Intelligent manufacturing v3.14.4 release, ERP mall\",\"author\":\"资源站点\",\"tag\":[\"Skyeye\"],\"date\":\"2024-09-09T00:00:00.000Z\",\"cover\":\"/assets/img/news/Skyeye-3.14.4-0.png\",\"head\":[[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"Intelligent manufacturing v3.14.4 release, ERP mall\\\",\\\"image\\\":[\\\"https://vuepress-theme-hope-docs-demo.netlify.app/assets/img/news/Skyeye-3.14.4-0.png\\\",\\\"https://vuepress-theme-hope-docs-demo.netlify.app/assets/img/news/Skyeye-3.14.4-1.png\\\",\\\"https://vuepress-theme-hope-docs-demo.netlify.app/assets/img/news/Skyeye-3.14.4-2.png\\\",\\\"https://vuepress-theme-hope-docs-demo.netlify.app/assets/img/news/Skyeye-3.14.4-3.png\\\"],\\\"datePublished\\\":\\\"2024-09-09T00:00:00.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"资源站点\\\"}]}\"],[\"meta\",{\"property\":\"og:url\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/news/Skyeye-3.14.4.html\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"Intelligent manufacturing v3.14.4 release, ERP mall\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"Intelligent manufacturing integrated management system [SpringBoot2-rapid development platform ], suitable for the management of manufacturing, construction, automobile industry...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:image\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/assets/img/news/Skyeye-3.14.4-0.png\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"en-US\"}],[\"meta\",{\"property\":\"og:locale:alternate\",\"content\":\"zh-CN\"}],[\"meta\",{\"name\":\"twitter:card\",\"content\":\"summary_large_image\"}],[\"meta\",{\"name\":\"twitter:image:src\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/assets/img/news/Skyeye-3.14.4-0.png\"}],[\"meta\",{\"name\":\"twitter:image:alt\",\"content\":\"Intelligent manufacturing v3.14.4 release, ERP mall\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"资源站点\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"Skyeye\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2024-09-09T00:00:00.000Z\"}],[\"link\",{\"rel\":\"alternate\",\"hreflang\":\"zh-cn\",\"href\":\"https://vuepress-theme-hope-docs-demo.netlify.app/zh/news/Skyeye-3.14.4.html\"}],[\"meta\",{\"name\":\"News\"}]],\"description\":\"Intelligent manufacturing integrated management system [SpringBoot2-rapid development platform ], suitable for the management of manufacturing, construction, automobile industry...\"},\"readingTime\":{\"minutes\":1.22,\"words\":366},\"filePathRelative\":\"news/Skyeye-3.14.4.md\",\"autoDesc\":true}")
export { comp, data }

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
