import comp from "E:/code/newstudy/new/dromara.github.io/src/.vuepress/.temp/pages/news/WarmFlow-1.2.6.html.vue"
const data = JSON.parse("{\"path\":\"/news/WarmFlow-1.2.6.html\",\"title\":\"Warm Flow 1.2.6 Version update, support process status customization\",\"lang\":\"en-US\",\"frontmatter\":{\"title\":\"Warm Flow 1.2.6 Version update, support process status customization\",\"author\":\"warm flow\",\"date\":\"2024-08-28T00:00:00.000Z\",\"cover\":\"/assets/img/news/WarmFlow-1.2.6-0.png\",\"head\":[[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"Warm Flow 1.2.6 Version update, support process status customization\\\",\\\"image\\\":[\\\"https://vuepress-theme-hope-docs-demo.netlify.app/assets/img/news/WarmFlow-1.2.6-0.png\\\",\\\"https://vuepress-theme-hope-docs-demo.netlify.app/assets/img/qrcode_zsxq.webp\\\"],\\\"datePublished\\\":\\\"2024-08-28T00:00:00.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"warm flow\\\"}]}\"],[\"meta\",{\"property\":\"og:url\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/news/WarmFlow-1.2.6.html\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"Warm Flow 1.2.6 Version update, support process status customization\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"warm-flow 1.2.6 Version update This change Process status: can receive external transmission, can support string add api: add to get next node information id generation: support...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:image\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/assets/img/news/WarmFlow-1.2.6-0.png\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"en-US\"}],[\"meta\",{\"property\":\"og:locale:alternate\",\"content\":\"zh-CN\"}],[\"meta\",{\"name\":\"twitter:card\",\"content\":\"summary_large_image\"}],[\"meta\",{\"name\":\"twitter:image:src\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/assets/img/news/WarmFlow-1.2.6-0.png\"}],[\"meta\",{\"name\":\"twitter:image:alt\",\"content\":\"Warm Flow 1.2.6 Version update, support process status customization\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"warm flow\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2024-08-28T00:00:00.000Z\"}],[\"link\",{\"rel\":\"alternate\",\"hreflang\":\"zh-cn\",\"href\":\"https://vuepress-theme-hope-docs-demo.netlify.app/zh/news/WarmFlow-1.2.6.html\"}],[\"meta\",{\"name\":\"News\"}]],\"description\":\"warm-flow 1.2.6 Version update This change Process status: can receive external transmission, can support string add api: add to get next node information id generation: support...\"},\"readingTime\":{\"minutes\":2.15,\"words\":644},\"filePathRelative\":\"news/WarmFlow-1.2.6.md\",\"autoDesc\":true}")
export { comp, data }

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
